- name : Install Nginx using play book
  hosts : web
  become : yes
  tasks :
    - name : Install nginx
      ansible.builtin.dnf:
       name : nginx
       state : present

    - name : Start nginx service
      ansible.builtin.service:
        name : nginx
        state: started
