# Variables to print, We have use variables in ansible multiple ways. Some of the examples are below.
- name: Printing variables
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    DURATION: 120
    TRAINED: "https://www.joindevops.com/"
  tasks:
    - name: Print the Information of this course without variables
      ansible.builtin.debug:
        msg: "Hi, I am Venkatesh. I am learning DevOps. Course duration is 120 HRS. Trained from JoinDevOps"

    - name: Print the same information using variables
      ansible.builtin.debug:
        msg: "Hi, I am learning {{ COURSE }} from {{ TRAINED }}, Course duration is {{ DURATION }}"