# This playbook is to print data types information in Ansible
- name: DevOps Course Information
  hosts: local
  connection: local
  vars:
    course: "DevOps with AWS"  # String
    duration: 120  # Number (in hours)
    topics:  # List of topics covered
      - Linux
      - Shell
      - Ansible
      - Terraform
      - Docker
      - Kubernetes
      - Git
      - Jenkins
    live: true  # Boolean indicating if the training is live
    tools:  # Dictionary of tools used
      ci: Jenkins
      cd: Ansible
      cloud:
        aws:
          - IAM
          - S3

  tasks:
    - name: Print the course information
      ansible.builtin.debug:
        msg: |
          Hi, I am learning {{ course }}.
          Duration is {{ duration }} hours.
          Topics covered as part of this course: {{ topics }}.
          This is a live training: {{ live }}.
          Tools used as part of this training: {{ tools }}
            - CI Tool: {{ tools.ci }}
            - CD Tool: {{ tools.cd }}
            - Cloud Services: {{ tools.cloud.aws | join(', ') }}