# This is to check the number is greater than or less than in ansible using conditions.
- name: Check if the given number is greater than or less than 10
  hosts: local
  connection: local
  vars_prompt:
    name: Number
    prompt: Please enter the number you are trying to verify
    private: false
  tasks:
    - name: Validate the input is an integer
      ansible.builtin.assert:
        that:
          - number is match("^[0-9]+$")
        fail_msg: "The input {{ Number }} is not a valid integer."

    - name: Print the number if less than 10
      ansible.builtin.debug:
        msg: "Given number {{ Number }} is less than 10"
      when: Number | int < 10

    - name: Print the number of it is greater than or equal to 10
      ansible.builtin.debug:
        msg: "Given number {{ Number }} is greater than or equal to 10"
      when: Number | int >= 10

      # Failed with the error because by default data entered through prompt is considered as string and you cannot compare it with Int.
      # Add the filter to convert the data type to int to resolve the issue.