# Install nginx on the ansible facts
- name: Install nginx based on the ansible facts
  hosts: web
  become: yes
  gather_facts: yes
  tasks:
    - name: Gather facts and print stats
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Install nginx if the the OS is RedHat
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install nginx if the os familt is Ubuntu
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"