# Install nginx based on the ansible facts
- name: Install nginx based on the ansible facts
  hosts: web
  become: yes
  gather_facts: yes
  tasks:
    - name: Gather facts and print stats
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Install nginx on RedHat-based systems
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install nginx on Debian-based systems
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
